### ISSUE TITLE
Typo on line 29

### ISSUE THREAD

**Issue by charleshoots** [ZahraZali/NoiseCut#1]
https://github.com/ZahraZali/NoiseCut/blob/3b55c7846486ab7bf974ffeed71a1510bb62253b/src/noisecut.py#L29C8-L29C8

Should be:
elif win_length_samples is not None and win_length is not None:

**Comment by ZahraZali** [comment]
Thanks. It is now corrected.

**Comment by ZahraZali** [comment]
Thanks. It is now corrected.
